services:
  face-rknn:
    build: .
    image: face-rknn-demo:2.3.2
    devices:
      - /dev/dri/card1:/dev/dri/card1
    volumes:
      - ${INPUT_PATH:-./assets/test.jpg}:/input.jpg:ro
      - ./output:/output
    command: ["/input.jpg", "/output/face_result.ppm", "/app/models"]

  gstreamer-face:
    build:
      context: .
      dockerfile: Dockerfile.gstreamer
    image: face-rknn-gstreamer:1.0.0
    environment:
      GST_VIDEO_CONVERT_USE_RGA: "1"
      GST_VIDEO_CONVERT_RGA_DMA_HEAP: /dev/dma_heap/cma
    privileged: true
    volumes:
      - ${GST_INPUT_PATH:-./assets/test.jpg}:/input.jpg:ro
      - ./output:/output
      - /usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstrockchipmpp.so:/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstrockchipmpp.so:ro
      - /lib/aarch64-linux-gnu/librockchip_mpp.so.0:/usr/lib/aarch64-linux-gnu/librockchip_mpp.so.1:ro
      - /usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstvideoparsersbad.so:/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstvideoparsersbad.so:ro
      - /usr/lib/aarch64-linux-gnu/libgstcodecparsers-1.0.so.0.2402.0:/usr/lib/aarch64-linux-gnu/libgstcodecparsers-1.0.so.0:ro
    command:
      - -e
      - filesrc
      - location=/input.jpg
      - "!"
      - jpegdec
      - "!"
      - videoconvert
      - "!"
      - video/x-raw,format=RGB
      - "!"
      - rknnfacemesh
      - "!"
      - jpegenc
      - "!"
      - filesink
      - location=/output/gstreamer-face.jpg
